language: groovy
sudo: false

jdk:
    - oraclejdk7

before_install:
    - git clone --depth 1 git://github.com/thehyve/transmart-travis.git ~/ts-travis
    - git clone --depth 1 git://github.com/transmart/transmart-data.git ~/transmart-data
    - source ~/ts-travis/init.sh
    - source ~/ts-travis/grails_inline.sh
    - source ~/ts-travis/maven_dep.sh
    - sudo apt-key adv --keyserver keyserver.ubuntu.com --recv 3375DA21
    - echo deb http://apt.thehyve.net/internal/ trusty main | sudo tee /etc/apt/sources.list.d/hyve_internal.list
    - sudo apt-get update

install:
    - sudo apt-get install -qq php5-cli php5-json subversion groovy
    - maybe_build_maven_dep $(travis_get_owner)/transmart-core-api core-api
    - maybe_make_inline_grails_dep $(travis_get_owner)/transmart-core-db core-db . transmart-core-db-tests

before_script:
	- (cd ~/transmart-data/; make -C env ../vars; ./travis-test R)

script:
    - grails refresh-dependencies --non-interactive
    - grails test-app --non-interactive --stacktrace

